name: CLI CI (D, optimized)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build for release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build
        run: dub build -b release

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: hashtrack
          path: hashtrack
