steps:
    - uses: actions/checkout@v2

    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest

    - name: Build
      run: dub
      on: push

    - name: Test
      run: dub test
      on: [push, pull_request]
