name: CLI CI (D)

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build
        run: dub

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Test
        run: dub test
